title: Eiríkur Jónsson # your name (or website title) here
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science student at SDU 
  <br><br>
  These projects are my personal projects, done because I think they are interesting and cool.j
  <br><br>
Main Skill Set:
    - Python
    - R
    - Machine Learning
    - Deep Learning
    - Data Visualization
    - Data Transformation
  <br><br>
  <a href="https://www.linkedin.com/in/eirikur-jonsson-92a1b440/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: #UA-000000-0 # your Google Analytics tracking ID here

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
